### PR TITLE
Fix panel size on Windows

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by wagnerand** [comment]
r=trivial

**Comment by tofumatt** [comment]
It's always the trivial patches someone finds a bug in! 😉

**Comment by wagnerand** [comment]
omg.

**Comment by wagnerand** [comment]
Wait, where's the bug?

**Comment by tofumatt** [comment]
Haha no I was just poking fun at r=trivial. Nothing’s wrong, sorry for the
false alarm 😂

**Comment by wagnerand** [comment]
*phew*

**Pull request merged**
